version: '3.5'

services:
  node:
        image: 'img_vue'
        ports:
        - '8080:80'
        volumes:
        - '.:/app'
        command: "tail -f /dev/null"
        networks:
            - docker_services
    

networks:
  docker_services:
    external: true